[env:xiao_esp32s3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
framework = arduino
lib_deps =
    h2zero/NimBLE-Arduino@^2.1.2
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    bblanchon/ArduinoJson@^7.3.0
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
    -DCONFIG_NIMBLE_CPP_ATT_MTU=512
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_SW_COEXIST_ENABLE=1
    -DCONFIG_ESP32S3_BROWNOUT_DET=1
    -DARDUINO_LOOP_STACK_SIZE=16384
